/// <reference types='vitest' />
import { defineConfig } from 'vite';
import dts from 'vite-plugin-dts';
import { readdirSync, writeFileSync } from 'fs';
import * as path from 'path';
import react from '@vitejs/plugin-react';

function generateEntries() {
  const entries: Record<string, string> = {};

  const componentFiles = readdirSync(path.join(__dirname, 'src/components'))
    .filter(file => file.endsWith('.tsx'))
    .map(file => file.replace('.tsx', ''));

  componentFiles.forEach(component => {
    entries[`components/${component}`] = `src/components/${component}.tsx`;
  });

  const libFiles = readdirSync(path.join(__dirname, 'src/lib'))
    .filter(file => file.endsWith('.ts'))
    .map(file => file.replace('.ts', ''));

  libFiles.forEach(lib => {
    entries[`lib/${lib}`] = `src/lib/${lib}.ts`;
  });

  return entries;
}

function generateIndexFile() {
  const componentsDir = path.join(__dirname, 'src/components');
  const libDir = path.join(__dirname, 'src/lib');

  let content =
    '// Auto-generated index file\n// Dont edit this file manually\n// It is generated by vite.config.ts on build\n\n';

  // Add component exports
  const componentFiles = readdirSync(componentsDir)
    .filter(file => file.endsWith('.tsx'))
    .map(file => file.replace('.tsx', ''));

  if (componentFiles.length > 0) {
    content += '// Export all components\n';
    componentFiles.forEach(component => {
      content += `export * from './components/${component}';\n`;
    });
    content += '\n';
  }

  // Add lib exports
  const libFiles = readdirSync(libDir)
    .filter(file => file.endsWith('.ts'))
    .map(file => file.replace('.ts', ''));

  if (libFiles.length > 0) {
    content += '// Export utilities\n';
    libFiles.forEach(lib => {
      content += `export * from './lib/${lib}';\n`;
    });
  }

  writeFileSync(path.join(__dirname, 'src/index.ts'), content);
}

export default defineConfig({
  root: __dirname,
  cacheDir: '../../node_modules/.vite/packages/ui',
  resolve: {
    alias: {
      '@packages/ui': path.resolve(__dirname, './src'),
    },
  },
  plugins: [
    react(),
    dts({
      entryRoot: 'src',
      tsconfigPath: path.join(__dirname, 'tsconfig.lib.json'),
    }),
    // Custom plugin to generate index file
    {
      name: 'generate-index',
      buildStart() {
        generateIndexFile();
      },
    },
  ],
  // Uncomment this if you are using workers.
  // worker: {
  //  plugins: [ nxViteTsPaths() ],
  // },
  // Configuration for building your library.
  // See: https://vitejs.dev/guide/build.html#library-mode
  build: {
    outDir: './dist',
    emptyOutDir: true,
    reportCompressedSize: true,
    commonjsOptions: {
      transformMixedEsModules: true,
    },
    lib: {
      entry: generateEntries(),
      name: 'ui',
      formats: ['es' as const],
    },
    rollupOptions: {
      // External packages that should not be bundled into your library.
      external: ['react', 'react-dom', 'react/jsx-runtime'],
    },
  },
  test: {
    watch: false,
    globals: true,
    environment: 'jsdom',
    include: ['src/**/*.test.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],
    reporters: ['default'],
    coverage: {
      reportsDirectory: './test-output/vitest/coverage',
      provider: 'v8' as const,
    },
  },
});
